// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-qmpZDtdCDLtUz6z4BvWo6opiQee_W-Q',
    appId: '1:134309525940:web:6431d3a37b2bbec7335ae1',
    messagingSenderId: '134309525940',
    projectId: 'nuntium-a5bcf',
    authDomain: 'nuntium-a5bcf.firebaseapp.com',
    storageBucket: 'nuntium-a5bcf.appspot.com',
    measurementId: 'G-XQ6L71DSPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjRaFLKg5Uw5G0AWok7plk2BUCb_FlL_E',
    appId: '1:134309525940:android:3ff5694886b0c3c1335ae1',
    messagingSenderId: '134309525940',
    projectId: 'nuntium-a5bcf',
    storageBucket: 'nuntium-a5bcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQKN3F-miQ5aE5u20cwA-lVx6jgHpz18o',
    appId: '1:134309525940:ios:35f52fd6da9f4f47335ae1',
    messagingSenderId: '134309525940',
    projectId: 'nuntium-a5bcf',
    storageBucket: 'nuntium-a5bcf.appspot.com',
    iosClientId: '134309525940-3vt881genso2ttgvq1k8vsahspadr4bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.nuntium',
  );
}
